[package]
name = "vicon-sys"
version = "0.1.0"
edition = "2021"

[dependencies]

# Error handling.
snafu = { version = "0.7.1", default-features = false }

[build-dependencies]

# Native C FFI generation.
bindgen = "0.66.1"